AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with SSH access

Parameters:
  AMIID:
    Type: String
    Default: ami-0c02fb55956c7d316
  InstanceType:
    Type: String
    Default: t2.micro
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  VPCId:
    Type: AWS::EC2::VPC::Id

Resources:

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIID
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      KeyName: assignment3-key       # ✅ Add this line
      Tags:
        - Key: Name
          Value: Assignment3-EC2

Outputs:
  EC2PublicIP:
    Description: Public IP of EC2
    Value: !GetAtt EC2Instance.PublicIp
